version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: thelounge-umbrel-app_web_1
      APP_PORT: 9000

  web:
    image: ghcr.io/thelounge/thelounge:latest
    init: true
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    environment:
      APP_PASSWORD: $APP_PASSWORD
    volumes:
      - ${APP_DATA_DIR}/data:/var/opt/thelounge
    entrypoint:
      - /bin/sh
      - /var/opt/thelounge/init.sh
